name: gearshare_vn
description: "An unusual Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_local_notifications: ^17.1.0 
  permission_handler: ^12.0.1
  fl_chart: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_rm_blank.png"
  color: "#0F8B74" 

flutter_native_splash:
  android: true
  ios: true
  image: assets/logo_rm_blank.png
  color: "#0F8B74"
  fullscreen: true
  android_gravity: center

